server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: "60s"
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/kick
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: djdkslsalasdfjklaskljflkjaslfjdjflskfjslfjalsfirksas
  access-exp: 12000
  header: Authorization
  prefix: Bearer